### PR TITLE
Refactor DataTableState2 and DataTableLiveState classes

### PR DESCRIPTION
**Pull request by elviskahoro**
This pull request improves the code quality and consistency in the `datatable_tutorial_utils.py` file. Key changes include:

1. Reordered imports for better readability.
2. Added type hints to several methods in the `DataTableState2` class.
3. Updated the docstring format for the `DataTableLiveState` class.
4. Improved the formatting of the `live_stream` method in `DataTableLiveState`.
5. Enhanced the `toggle_pause` method to return `None` when not running.

These changes aim to improve code maintainability and adhere to best practices for Python development.

### CODE REVIEW

**Comment by elviskahoro** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/reflex-dev/reflex-web/895?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#896** <a href="https://app.graphite.dev/github/pr/reflex-dev/reflex-web/896?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#895** <a href="https://app.graphite.dev/github/pr/reflex-dev/reflex-web/895?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#894** <a href="https://app.graphite.dev/github/pr/reflex-dev/reflex-web/894?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#893** <a href="https://app.graphite.dev/github/pr/reflex-dev/reflex-web/893?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#892** <a href="https://app.graphite.dev/github/pr/reflex-dev/reflex-web/892?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#891** <a href="https://app.graphite.dev/github/pr/reflex-dev/reflex-web/891?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#890** <a href="https://app.graphite.dev/github/pr/reflex-dev/reflex-web/890?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @elviskahoro and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by elviskahoro** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/reflex-dev/reflex-web/895?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#896** <a href="https://app.graphite.dev/github/pr/reflex-dev/reflex-web/896?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#895** <a href="https://app.graphite.dev/github/pr/reflex-dev/reflex-web/895?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#894** <a href="https://app.graphite.dev/github/pr/reflex-dev/reflex-web/894?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#893** <a href="https://app.graphite.dev/github/pr/reflex-dev/reflex-web/893?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#892** <a href="https://app.graphite.dev/github/pr/reflex-dev/reflex-web/892?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#891** <a href="https://app.graphite.dev/github/pr/reflex-dev/reflex-web/891?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#890** <a href="https://app.graphite.dev/github/pr/reflex-dev/reflex-web/890?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @elviskahoro and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by elviskahoro** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/reflex-dev/reflex-web/895?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#896** <a href="https://app.graphite.dev/github/pr/reflex-dev/reflex-web/896?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#895** <a href="https://app.graphite.dev/github/pr/reflex-dev/reflex-web/895?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#894** <a href="https://app.graphite.dev/github/pr/reflex-dev/reflex-web/894?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#893** <a href="https://app.graphite.dev/github/pr/reflex-dev/reflex-web/893?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#892** <a href="https://app.graphite.dev/github/pr/reflex-dev/reflex-web/892?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#891** <a href="https://app.graphite.dev/github/pr/reflex-dev/reflex-web/891?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#890** <a href="https://app.graphite.dev/github/pr/reflex-dev/reflex-web/890?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @elviskahoro and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by picklelo — APPROVED** [review]

**Comment by elviskahoro** [comment]
### Merge activity

* **Sep 3, 10:39 PM EDT**: @elviskahoro started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/reflex-dev/reflex-web/895).

**Pull request merged**
