### PR TITLE
add new var documentation

### PR DESCRIPTION
**Pull request by adhami3310**
@elviskahoro

### CODE REVIEW

**Comment by elviskahoro** [comment]
@linear #ENG-1983

**Comment by elviskahoro** [comment]
ENG-1983

**Comment by elviskahoro** [comment]
Fixes ENG-1983

**Comment by elviskahoro** [comment]
@adhami3310 I'm better on linear than in github cause my notifications are more streamlined.

**Comment by Alek99** [comment]
What's the status on this @elviskahoro are you leaving feedback on comments on the PR or addressing on linear? I think its better to do everything in the PR that's way it stays in a single place.

**Comment by elviskahoro** [comment]
> What's the status on this @elviskahoro are you leaving feedback on comments on the PR or addressing on linear? I think its better to do everything in the PR that's way it stays in a single place.

@adhami3310 said the var system has already changed again and so we're gonna revisit these once they're finalized + after fixing flexdown
@picklelo has some context on flexdown I think??

**Review by elviskahoro — APPROVED** [review]

**Comment by elviskahoro** [comment]
Closing in favor of:
https://github.com/reflex-dev/reflex-web/pull/937

**Pull request closed without merging**
