### PR TITLE
Fix a few issues on the web page

### PR DESCRIPTION
**Pull request by HongyuHansonYao**
1. Remove "show code" button on the interactive demo section, 
2. Bring back navbar,
3. Make call to actions buttons bigger
4. Put newsletter signup in main section

### CODE REVIEW

**Comment by masenf** [comment]
more commits to come?

**Comment by HongyuHansonYao** [comment]
> more commits to come?

Yes!

**Comment by HongyuHansonYao** [comment]
Fixed three small things, the news letter need more refactoring than I expected, will be on a different PR.

**Comment by HongyuHansonYao** [comment]
This PR is now ready for review

**Review by picklelo — APPROVED** [review]

**Pull request merged**
